### ISSUE TITLE
Infografía de Gregorio Osorio

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Gregorio012#2]
[Infografia_GestiondeProyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Gregorio012/files/12457942/Infografia_GestiondeProyectos.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecha y revisada...
